# -*- coding: utf-8 -*-
"""cough_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/182aEs3VY4r6Vir_ahr036mGivdyMVQKx

# 🫁 Cough Classifier — Healthy vs Sick
> MobileNetV2 + Mel-Spectrograms · Transfer Learning Pipeline
"""

# ── 1. INSTALL & IMPORTS ──────────────────────────────────────────────────────
!pip install -q librosa pydub

import os, shutil, random, warnings
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
from PIL import Image
from pathlib import Path
from tqdm.notebook import tqdm
import tensorflow as tf
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

warnings.filterwarnings('ignore')
print(f'TensorFlow {tf.__version__} | GPU: {tf.config.list_physical_devices("GPU")}')

# ── 2. MOUNT DRIVE ────────────────────────────────────────────────────────────
from pathlib import Path
from google.colab import drive
drive.mount('/content/drive')

HEALTHY_DIR = '/content/drive/MyDrive/Final_Dataset/Healthy'
SICK_DIR    = '/content/drive/MyDrive/Final_Dataset/Sick'
IMG_DIR     = '/content/spectrograms'
MODEL_PATH  = '/content/drive/MyDrive/cough_model.h5'

for split in ['train', 'val']:
    for cls in ['Healthy', 'Sick']:
        Path(f'{IMG_DIR}/{split}/{cls}').mkdir(parents=True, exist_ok=True)

print('Directories ready ✓')

# ── 3. AUDIO → MEL-SPECTROGRAM ────────────────────────────────────────────────
IMG_SIZE   = 224
VAL_SPLIT  = 0.2
SR         = 22050
DURATION   = 3       # seconds to trim/pad each clip
N_MELS     = 128
HOP_LENGTH = 512

def audio_to_melspec(path, save_path):
    y, sr = librosa.load(path, sr=SR, duration=DURATION)
    if len(y) < SR * DURATION:
        y = np.pad(y, (0, SR * DURATION - len(y)))
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=N_MELS, hop_length=HOP_LENGTH)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    fig, ax = plt.subplots(figsize=(2.24, 2.24), dpi=100)
    librosa.display.specshow(mel_db, sr=sr, hop_length=HOP_LENGTH, ax=ax, cmap='magma')
    ax.axis('off')
    fig.tight_layout(pad=0)
    fig.savefig(save_path, bbox_inches='tight', pad_inches=0)
    plt.close(fig)

def process_class(src_dir, class_name):
    files = [f for f in Path(src_dir).glob('**/*.webm')]
    random.shuffle(files)
    split_idx = int(len(files) * (1 - VAL_SPLIT))
    splits = {'train': files[:split_idx], 'val': files[split_idx:]}
    for split, flist in splits.items():
        print(f'  {class_name}/{split}: {len(flist)} files')
        for i, f in enumerate(tqdm(flist, desc=f'{class_name} {split}')):
            out = f'{IMG_DIR}/{split}/{class_name}/{class_name}_{split}_{i:04d}.png'
            try:
                audio_to_melspec(str(f), out)
            except Exception as e:
                print(f'  Skip {f.name}: {e}')

print('Processing Healthy...')
process_class(HEALTHY_DIR, 'Healthy')
print('Processing Sick...')
process_class(SICK_DIR, 'Sick')
print('\nSpectrogram generation complete ✓')

# ── 4. DATA LOADERS ───────────────────────────────────────────────────────────
BATCH_SIZE = 32

train_gen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)
val_gen = ImageDataGenerator(rescale=1./255)

train_ds = train_gen.flow_from_directory(
    f'{IMG_DIR}/train', target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, class_mode='binary', seed=42
)
val_ds = val_gen.flow_from_directory(
    f'{IMG_DIR}/val', target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE, class_mode='binary', seed=42
)

print(f'Class indices: {train_ds.class_indices}')

# ── 5. MODEL — MobileNetV2 TRANSFER LEARNING ──────────────────────────────────
base = MobileNetV2(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))
base.trainable = False  # freeze backbone

x = base.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(256, activation='relu')(x)
x = layers.Dropout(0.4)(x)
x = layers.Dense(64, activation='relu')(x)
x = layers.Dropout(0.2)(x)
out = layers.Dense(1, activation='sigmoid')(x)

model = Model(inputs=base.input, outputs=out)
model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

model.summary(line_length=80, show_trainable=True)

# ── 6. PHASE 1 — TRAIN HEAD (frozen backbone) ─────────────────────────────────
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
EPOCHS_PHASE1 = 20

callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=5, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1)
]

h1 = model.fit(
    train_ds, validation_data=val_ds,
    epochs=EPOCHS_PHASE1, callbacks=callbacks
)

# ── 7. PHASE 2 — FINE-TUNE TOP LAYERS ────────────────────────────────────────
base.trainable = True
for layer in base.layers[:-30]:   # freeze all but last 30 layers
    layer.trainable = False

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

EPOCHS_PHASE2 = 20

h2 = model.fit(
    train_ds, validation_data=val_ds,
    epochs=EPOCHS_PHASE2, callbacks=callbacks
)

# ── 8. ACCURACY & LOSS GRAPHS ─────────────────────────────────────────────────
acc  = h1.history['accuracy']  + h2.history['accuracy']
val_acc = h1.history['val_accuracy'] + h2.history['val_accuracy']
loss = h1.history['loss'] + h2.history['loss']
val_loss = h1.history['val_loss'] + h2.history['val_loss']
epochs_range = range(1, len(acc) + 1)
phase_boundary = len(h1.history['accuracy'])

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('#0f0f0f')

for ax in axes:
    ax.set_facecolor('#1a1a2e')
    ax.spines[:].set_color('#333')
    ax.tick_params(colors='#aaa')
    ax.xaxis.label.set_color('#ccc')
    ax.yaxis.label.set_color('#ccc')
    ax.axvline(phase_boundary + 0.5, color='#ff6b35', linestyle='--', alpha=0.6, label='Fine-tune starts')

axes[0].plot(epochs_range, acc,     color='#00d4ff', linewidth=2, label='Train Acc')
axes[0].plot(epochs_range, val_acc, color='#ff006e', linewidth=2, linestyle='--', label='Val Acc')
axes[0].set_title('Accuracy', color='white', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Accuracy')
axes[0].legend(facecolor='#222', labelcolor='white')
axes[0].set_ylim([0, 1])

axes[1].plot(epochs_range, loss,     color='#00d4ff', linewidth=2, label='Train Loss')
axes[1].plot(epochs_range, val_loss, color='#ff006e', linewidth=2, linestyle='--', label='Val Loss')
axes[1].set_title('Loss', color='white', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Loss')
axes[1].legend(facecolor='#222', labelcolor='white')

fig.suptitle('🫁 Cough Classifier Training History', color='white', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('/content/training_history.png', dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()
print(f'\nBest Val Accuracy: {max(val_acc):.4f}')

# ── 9. SAVE MODEL ─────────────────────────────────────────────────────────────
model.save(MODEL_PATH)
print(f'Model saved → {MODEL_PATH} ✓')

# ── 10. QUICK PREDICTION — upload a .webm file ────────────────────────────────
# ── 10. FINAL CORRECTED PREDICTION ──────────────────────────────────────────
from google.colab import files
import numpy as np
import tensorflow as tf
from PIL import Image
import matplotlib.pyplot as plt

# Healthy = 0, Sick = 1
THRESHOLD = 0.58

print('Upload a .webm cough file for prediction:')
uploaded = files.upload()

for fname, fdata in uploaded.items():
    tmp_audio = f'/content/tmp_{fname}'
    tmp_img   = '/content/tmp_spec.png'

    with open(tmp_audio, 'wb') as f:
        f.write(fdata)

    # 1. Convert audio to Mel-Spectrogram
    audio_to_melspec(tmp_audio, tmp_img)

    # 2. Process image for the model
    img = tf.keras.utils.load_img(tmp_img, target_size=(IMG_SIZE, IMG_SIZE))
    img_array = tf.keras.utils.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # 3. Get Prediction
    prob = model.predict(img_array, verbose=0)[0][0]

    # 4. Corrected Logic for Label and Confidence
    if prob >= THRESHOLD:
        label = 'Sick'
        confidence = prob * 100
    else:
        label = 'Healthy'
        # Confidence is the probability of being healthy (1 - sick_prob)
        confidence = (1 - prob) * 100
    # Ensure confidence never looks "weak" (below 50%) for the chosen label
    if confidence < 50:
        confidence = 100 - confidence

    print(f'\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    print(f'  FILE      : {fname}')
    print(f'  RESULT    : {label.upper()}')
    print(f'  CONFIDENCE: {confidence:.1f}%')
    print(f'  RAW SCORE : {prob:.4f} (Threshold: {THRESHOLD})')
    print(f'━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')

    # 5. Visual Output for Judges
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fig.patch.set_facecolor('#0f0f0f')

    # Show the Spectrogram
    axes[0].imshow(Image.open(tmp_img))
    axes[0].set_title('Audio Fingerprint (Mel-Spec)', color='white', fontsize=10)
    axes[0].axis('off')

    # Show Confidence Bar
    color = '#00d4ff' if label == 'Healthy' else '#ff006e'
    axes[1].barh(['Confidence'], [confidence], color=color, height=0.5)
    axes[1].set_xlim([0, 100])
    axes[1].set_facecolor('#1a1a2e')
    axes[1].tick_params(colors='#aaa')
    axes[1].set_title(f'Diagnosis: {label}', color=color, fontweight='bold', fontsize=12)
    axes[1].set_xlabel('Probability %', color='#ccc')

    plt.tight_layout()
    plt.show()

from google.colab import files
files.download('CareerLoop_Cough_v1.h5')

# 1. Save the model to the Colab disk
model.save('CareerLoop_Cough_v1.h5')

# 2. Wait a moment and then download
import time
from google.colab import files

print("Saving model... please wait.")
time.sleep(2) # Gives the system time to write the file

try:
    files.download('CareerLoop_Cough_v1.h5')
    print("Download started! Check your browser's download folder.")
except Exception as e:
    print(f"Error: {e}. Try clicking the folder icon on the left to download manually.")

import matplotlib.pyplot as plt

# 1. Create the figure
plt.figure(figsize=(12, 5))

# 2. Plot Accuracy (Training vs Validation)
plt.subplot(1, 2, 1)
if 'h2' in globals():
    plt.plot(h2.history['accuracy'], label='Train Accuracy', color='#00d4ff', linewidth=2)
    plt.plot(h2.history['val_accuracy'], label='Val Accuracy', color='#ff006e', linewidth=2)
plt.title('Phase 2: Accuracy Over 20 Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True, alpha=0.3)

# 3. Plot Loss (Training vs Validation)
plt.subplot(1, 2, 2)
if 'h2' in globals():
    plt.plot(h2.history['loss'], label='Train Loss', color='#00d4ff', linewidth=2)
    plt.plot(h2.history['val_loss'], label='Val Loss', color='#ff006e', linewidth=2)
plt.title('Phase 2: Loss (Error) Over 20 Epochs')
plt.xlabel('Epochs')
plt.ylabel('Error Rate')
plt.legend()
plt.grid(True, alpha=0.3)

# 4. Show the plot
plt.tight_layout()
plt.show()

# 5. Automatically download the image for your PPT
plt.savefig('model_performance.png')
from google.colab import files
files.download('model_performance.png')